title: Elemecca
tagline:
url: http://blog.maltera.com
paginate: 20
baseurl:  ""

timezone: America/Los_Angeles

permalink: pretty

author:
  name: Sam Hanes
  email: sam@maltera.com

sass:
  sass_dir:          _sass
  style:            :compressed

defaults:
  - scope:
      type: posts
    values:
      layout: post
      author: Sam Hanes
  - scope:
      type: drafts
    values:
      layout: post
      author: Sam Hanes

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

gems:
  - jekyll-paginate
  - jekyll-gist
